
package calculator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatorService", targetNamespace = "http://calculator/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "subtract", targetNamespace = "http://calculator/", className = "calculator.Subtract")
    @ResponseWrapper(localName = "subtractResponse", targetNamespace = "http://calculator/", className = "calculator.SubtractResponse")
    @Action(input = "http://calculator/CalculatorService/subtractRequest", output = "http://calculator/CalculatorService/subtractResponse")
    public int subtract(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiply", targetNamespace = "http://calculator/", className = "calculator.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://calculator/", className = "calculator.MultiplyResponse")
    @Action(input = "http://calculator/CalculatorService/multiplyRequest", output = "http://calculator/CalculatorService/multiplyResponse")
    public int multiply(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://calculator/", className = "calculator.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://calculator/", className = "calculator.AddResponse")
    @Action(input = "http://calculator/CalculatorService/addRequest", output = "http://calculator/CalculatorService/addResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "divide", targetNamespace = "http://calculator/", className = "calculator.Divide")
    @ResponseWrapper(localName = "divideResponse", targetNamespace = "http://calculator/", className = "calculator.DivideResponse")
    @Action(input = "http://calculator/CalculatorService/divideRequest", output = "http://calculator/CalculatorService/divideResponse")
    public double divide(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
